.pragma library

// Emoji by name, for ":" in Pages: ":rocket" offers the rocket, and ":rocket:"
// is one. The names are GitHub's and Slack's (the first is the one shown);
// the other words find them too.

// [names, emoji, other words]
var LIST = [
  ["smile", "\u{1f604}", "happy joy glad"],
  ["smiley", "\u{1f603}", "happy joy"],
  ["grinning", "\u{1f600}", "happy smile"],
  ["grin", "\u{1f601}", "happy"],
  ["laughing satisfied", "\u{1f606}", "happy haha"],
  ["sweat_smile", "\u{1f605}", "phew relief"],
  ["rofl", "\u{1f923}", "lol laugh floor"],
  ["joy", "\u{1f602}", "lol laugh tears"],
  ["slightly_smiling_face", "\u{1f642}", "smile"],
  ["upside_down_face", "\u{1f643}", "silly"],
  ["wink", "\u{1f609}", "flirt"],
  ["blush", "\u{1f60a}", "proud happy"],
  ["innocent", "\u{1f607}", "angel halo"],
  ["smiling_face_with_three_hearts", "\u{1f970}", "love adore"],
  ["heart_eyes", "\u{1f60d}", "love crush"],
  ["star_struck", "\u{1f929}", "wow amazing"],
  ["kissing_heart", "\u{1f618}", "kiss love"],
  ["yum", "\u{1f60b}", "tasty delicious"],
  ["stuck_out_tongue", "\u{1f61b}", "tongue silly"],
  ["stuck_out_tongue_winking_eye", "\u{1f61c}", "silly joke"],
  ["zany_face", "\u{1f92a}", "crazy goofy"],
  ["money_mouth_face", "\u{1f911}", "rich money"],
  ["hugs hugging_face", "\u{1f917}", "hug"],
  ["hand_over_mouth", "\u{1f92d}", "oops giggle"],
  ["shushing_face", "\u{1f92b}", "quiet secret"],
  ["thinking", "\u{1f914}", "hmm think"],
  ["zipper_mouth_face", "\u{1f910}", "secret quiet"],
  ["raised_eyebrow", "\u{1f928}", "suspicious skeptic"],
  ["neutral_face", "\u{1f610}", "meh"],
  ["expressionless", "\u{1f611}", "blank"],
  ["no_mouth", "\u{1f636}", "silent"],
  ["smirk", "\u{1f60f}", "smug"],
  ["unamused", "\u{1f612}", "meh bored"],
  ["roll_eyes", "\u{1f644}", "eyeroll whatever"],
  ["grimacing", "\u{1f62c}", "awkward yikes"],
  ["lying_face", "\u{1f925}", "liar"],
  ["relieved", "\u{1f60c}", "calm relaxed"],
  ["pensive", "\u{1f614}", "sad thoughtful"],
  ["sleepy", "\u{1f62a}", "tired"],
  ["drooling_face", "\u{1f924}", "drool"],
  ["sleeping", "\u{1f634}", "sleep zzz tired"],
  ["mask", "\u{1f637}", "sick ill"],
  ["face_with_thermometer", "\u{1f912}", "sick fever ill"],
  ["nauseated_face", "\u{1f922}", "sick gross"],
  ["vomiting_face", "\u{1f92e}", "sick"],
  ["sneezing_face", "\u{1f927}", "cold sick"],
  ["hot_face", "\u{1f975}", "hot heat"],
  ["cold_face", "\u{1f976}", "cold freezing"],
  ["woozy_face", "\u{1f974}", "dizzy tipsy"],
  ["dizzy_face", "\u{1f635}", "dizzy"],
  ["exploding_head", "\u{1f92f}", "mind blown shocked"],
  ["cowboy_hat_face", "\u{1f920}", "cowboy"],
  ["partying_face", "\u{1f973}", "party celebrate birthday"],
  ["sunglasses", "\u{1f60e}", "cool"],
  ["nerd_face", "\u{1f913}", "nerd geek"],
  ["monocle_face", "\u{1f9d0}", "curious inspect"],
  ["confused", "\u{1f615}", "puzzled"],
  ["worried", "\u{1f61f}", "nervous"],
  ["slightly_frowning_face", "\u{1f641}", "sad"],
  ["open_mouth", "\u{1f62e}", "surprise wow"],
  ["hushed", "\u{1f62f}", "surprised"],
  ["astonished", "\u{1f632}", "shocked amazed"],
  ["flushed", "\u{1f633}", "embarrassed blush"],
  ["pleading_face", "\u{1f97a}", "please puppy"],
  ["frowning", "\u{1f626}", "sad"],
  ["anguished", "\u{1f627}", "pain"],
  ["fearful", "\u{1f628}", "scared afraid"],
  ["cold_sweat", "\u{1f630}", "nervous anxious"],
  ["disappointed_relieved", "\u{1f625}", "phew sad"],
  ["cry", "\u{1f622}", "sad tear"],
  ["sob", "\u{1f62d}", "cry sad tears"],
  ["scream", "\u{1f631}", "horror shocked"],
  ["confounded", "\u{1f616}", "frustrated"],
  ["persevere", "\u{1f623}", "struggle"],
  ["disappointed", "\u{1f61e}", "sad"],
  ["sweat", "\u{1f613}", "hard work"],
  ["weary", "\u{1f629}", "tired"],
  ["tired_face", "\u{1f62b}", "tired exhausted"],
  ["yawning_face", "\u{1f971}", "bored tired"],
  ["triumph", "\u{1f624}", "proud"],
  ["rage pout", "\u{1f621}", "angry mad"],
  ["angry", "\u{1f620}", "mad annoyed"],
  ["cursing_face", "\u{1f92c}", "swearing angry"],
  ["smiling_imp", "\u{1f608}", "devil evil"],
  ["imp", "\u{1f47f}", "devil angry"],
  ["skull", "\u{1f480}", "dead danger"],
  ["poop hankey", "\u{1f4a9}", "crap"],
  ["clown_face", "\u{1f921}", "clown"],
  ["ghost", "\u{1f47b}", "halloween boo"],
  ["alien", "\u{1f47d}", "ufo space"],
  ["robot", "\u{1f916}", "bot machine"],
  ["see_no_evil", "\u{1f648}", "monkey oops"],
  ["hear_no_evil", "\u{1f649}", "monkey"],
  ["speak_no_evil", "\u{1f64a}", "monkey secret"],
  ["heart", "\u2764\ufe0f", "love red"],
  ["orange_heart", "\u{1f9e1}", "love"],
  ["yellow_heart", "\u{1f49b}", "love"],
  ["green_heart", "\u{1f49a}", "love"],
  ["blue_heart", "\u{1f499}", "love"],
  ["purple_heart", "\u{1f49c}", "love"],
  ["black_heart", "\u{1f5a4}", "love"],
  ["white_heart", "\u{1f90d}", "love"],
  ["brown_heart", "\u{1f90e}", "love"],
  ["broken_heart", "\u{1f494}", "sad heartbreak"],
  ["two_hearts", "\u{1f495}", "love"],
  ["sparkling_heart", "\u{1f496}", "love"],
  ["heartpulse", "\u{1f497}", "love"],
  ["100", "\u{1f4af}", "perfect score hundred"],
  ["anger", "\u{1f4a2}", "angry"],
  ["boom collision", "\u{1f4a5}", "explode bang"],
  ["dizzy", "\u{1f4ab}", "star"],
  ["sweat_drops", "\u{1f4a6}", "water"],
  ["dash", "\u{1f4a8}", "fast wind"],
  ["speech_balloon", "\u{1f4ac}", "comment chat talk"],
  ["thought_balloon", "\u{1f4ad}", "think idea"],
  ["zzz", "\u{1f4a4}", "sleep"],
  ["wave", "\u{1f44b}", "hello hi bye goodbye"],
  ["raised_back_of_hand", "\u{1f91a}", "hand"],
  ["raised_hand hand", "\u270b", "stop high five"],
  ["vulcan_salute", "\u{1f596}", "spock"],
  ["ok_hand", "\u{1f44c}", "ok perfect"],
  ["pinching_hand", "\u{1f90f}", "small tiny"],
  ["v", "\u270c\ufe0f", "victory peace"],
  ["crossed_fingers", "\u{1f91e}", "luck hope"],
  ["love_you_gesture", "\u{1f91f}", "love"],
  ["metal", "\u{1f918}", "rock horns"],
  ["call_me_hand", "\u{1f919}", "call shaka"],
  ["point_left", "\u{1f448}", "left"],
  ["point_right", "\u{1f449}", "right"],
  ["point_up_2", "\u{1f446}", "up"],
  ["point_down", "\u{1f447}", "down"],
  ["point_up", "\u261d\ufe0f", "up"],
  ["+1 thumbsup", "\u{1f44d}", "yes like approve agree good"],
  ["-1 thumbsdown", "\u{1f44e}", "no dislike bad"],
  ["fist", "\u270a", "power"],
  ["facepunch punch", "\u{1f44a}", "fist bump"],
  ["clap", "\u{1f44f}", "applause bravo congrats"],
  ["raised_hands", "\u{1f64c}", "hooray celebrate"],
  ["open_hands", "\u{1f450}", "hug"],
  ["handshake", "\u{1f91d}", "deal agreement"],
  ["pray", "\u{1f64f}", "please thanks hope"],
  ["writing_hand", "\u270d\ufe0f", "write"],
  ["muscle", "\u{1f4aa}", "strong flex power"],
  ["brain", "\u{1f9e0}", "smart mind"],
  ["eyes", "\u{1f440}", "look see watch"],
  ["eye", "\u{1f441}\ufe0f", "see"],
  ["tongue", "\u{1f445}", "taste"],
  ["lips", "\u{1f444}", "kiss"],
  ["baby", "\u{1f476}", "child"],
  ["man", "\u{1f468}", "person"],
  ["woman", "\u{1f469}", "person"],
  ["shrug", "\u{1f937}", "whatever idk"],
  ["facepalm", "\u{1f926}", "ugh"],
  ["bow", "\u{1f647}", "sorry respect"],
  ["raising_hand", "\u{1f64b}", "question hand"],
  ["ok_woman", "\u{1f646}", "ok yes"],
  ["no_good", "\u{1f645}", "no stop"],
  ["runner running", "\u{1f3c3}", "run exercise"],
  ["walking", "\u{1f6b6}", "walk"],
  ["dancer", "\u{1f483}", "dance"],
  ["lotus_position", "\u{1f9d8}", "yoga meditate"],
  ["swimmer", "\u{1f3ca}", "swim"],
  ["bicyclist", "\u{1f6b4}", "bike cycle"],
  ["weight_lifting", "\u{1f3cb}\ufe0f", "gym exercise"],
  ["family", "\u{1f46a}", "home"],
  ["busts_in_silhouette", "\u{1f465}", "people team meeting group"],
  ["bust_in_silhouette", "\u{1f464}", "person user"],
  ["construction_worker", "\u{1f477}", "build work"],
  ["detective", "\u{1f575}\ufe0f", "spy sleuth"],
  ["technologist", "\u{1f9d1}\u200d\u{1f4bb}", "developer coder programmer"],
  ["teacher", "\u{1f9d1}\u200d\u{1f3eb}", "school professor"],
  ["student", "\u{1f9d1}\u200d\u{1f393}", "school graduate"],
  ["cook", "\u{1f9d1}\u200d\u{1f373}", "chef kitchen"],
  ["scientist", "\u{1f9d1}\u200d\u{1f52c}", "lab science"],
  ["artist", "\u{1f9d1}\u200d\u{1f3a8}", "painter art"],
  ["santa", "\u{1f385}", "christmas"],
  ["mage", "\u{1f9d9}", "wizard magic"],
  ["superhero", "\u{1f9b8}", "hero"],
  ["ninja", "\u{1f977}", "stealth"],
  ["zombie", "\u{1f9df}", "undead"],
  ["dog", "\u{1f436}", "pet puppy"],
  ["cat", "\u{1f431}", "pet kitten"],
  ["mouse", "\u{1f42d}", "animal"],
  ["rabbit", "\u{1f430}", "bunny"],
  ["fox_face", "\u{1f98a}", "fox"],
  ["bear", "\u{1f43b}", "animal"],
  ["panda_face", "\u{1f43c}", "panda"],
  ["koala", "\u{1f428}", "animal"],
  ["tiger", "\u{1f42f}", "animal"],
  ["lion", "\u{1f981}", "animal"],
  ["cow", "\u{1f42e}", "animal"],
  ["pig", "\u{1f437}", "animal"],
  ["frog", "\u{1f438}", "animal"],
  ["monkey_face", "\u{1f435}", "monkey"],
  ["chicken", "\u{1f414}", "bird"],
  ["penguin", "\u{1f427}", "bird linux"],
  ["bird", "\u{1f426}", "tweet"],
  ["owl", "\u{1f989}", "bird night wise"],
  ["unicorn", "\u{1f984}", "magic"],
  ["bee honeybee", "\u{1f41d}", "insect"],
  ["bug", "\u{1f41b}", "insect error"],
  ["butterfly", "\u{1f98b}", "insect"],
  ["snail", "\u{1f40c}", "slow"],
  ["turtle", "\u{1f422}", "slow"],
  ["snake", "\u{1f40d}", "python"],
  ["octopus", "\u{1f419}", "sea"],
  ["fish", "\u{1f41f}", "sea"],
  ["whale", "\u{1f433}", "sea"],
  ["dolphin", "\u{1f42c}", "sea"],
  ["crab", "\u{1f980}", "sea rust"],
  ["t-rex", "\u{1f996}", "dinosaur"],
  ["sauropod", "\u{1f995}", "dinosaur"],
  ["seedling", "\u{1f331}", "plant grow sprout"],
  ["herb", "\u{1f33f}", "plant leaf"],
  ["four_leaf_clover", "\u{1f340}", "luck"],
  ["cactus", "\u{1f335}", "plant desert"],
  ["evergreen_tree", "\u{1f332}", "tree pine"],
  ["deciduous_tree", "\u{1f333}", "tree"],
  ["palm_tree", "\u{1f334}", "tree beach"],
  ["fallen_leaf", "\u{1f342}", "autumn fall"],
  ["maple_leaf", "\u{1f341}", "autumn fall canada"],
  ["mushroom", "\u{1f344}", "fungus"],
  ["rose", "\u{1f339}", "flower"],
  ["sunflower", "\u{1f33b}", "flower"],
  ["tulip", "\u{1f337}", "flower"],
  ["cherry_blossom", "\u{1f338}", "flower spring"],
  ["bouquet", "\u{1f490}", "flowers"],
  ["earth_africa", "\u{1f30d}", "world globe"],
  ["earth_americas", "\u{1f30e}", "world globe"],
  ["earth_asia", "\u{1f30f}", "world globe"],
  ["globe_with_meridians", "\u{1f310}", "world web internet"],
  ["sunny", "\u2600\ufe0f", "sun weather"],
  ["partly_sunny", "\u26c5", "weather cloud"],
  ["cloud", "\u2601\ufe0f", "weather"],
  ["rainbow", "\u{1f308}", "weather pride"],
  ["umbrella", "\u2614", "rain weather"],
  ["snowflake", "\u2744\ufe0f", "winter cold snow"],
  ["snowman", "\u26c4", "winter snow"],
  ["zap", "\u26a1", "lightning fast power"],
  ["fire", "\u{1f525}", "hot lit flame"],
  ["droplet", "\u{1f4a7}", "water"],
  ["ocean", "\u{1f30a}", "wave sea water"],
  ["star", "\u2b50", "favorite"],
  ["star2", "\u{1f31f}", "glow shine"],
  ["sparkles", "\u2728", "shiny new magic"],
  ["crescent_moon", "\u{1f319}", "night"],
  ["full_moon", "\u{1f315}", "night moon"],
  ["new_moon", "\u{1f311}", "moon"],
  ["comet", "\u2604\ufe0f", "space"],
  ["tornado", "\u{1f32a}\ufe0f", "storm"],
  ["apple", "\u{1f34e}", "fruit"],
  ["green_apple", "\u{1f34f}", "fruit"],
  ["banana", "\u{1f34c}", "fruit"],
  ["grapes", "\u{1f347}", "fruit"],
  ["strawberry", "\u{1f353}", "fruit"],
  ["watermelon", "\u{1f349}", "fruit summer"],
  ["lemon", "\u{1f34b}", "fruit"],
  ["peach", "\u{1f351}", "fruit"],
  ["cherries", "\u{1f352}", "fruit"],
  ["avocado", "\u{1f951}", "fruit"],
  ["tomato", "\u{1f345}", "vegetable"],
  ["carrot", "\u{1f955}", "vegetable"],
  ["corn", "\u{1f33d}", "vegetable"],
  ["hot_pepper", "\u{1f336}\ufe0f", "spicy chili"],
  ["bread", "\u{1f35e}", "toast"],
  ["croissant", "\u{1f950}", "breakfast"],
  ["cheese", "\u{1f9c0}", "food"],
  ["egg", "\u{1f95a}", "breakfast"],
  ["fried_egg cooking", "\u{1f373}", "breakfast pan"],
  ["bacon", "\u{1f953}", "breakfast"],
  ["pizza", "\u{1f355}", "food"],
  ["hamburger", "\u{1f354}", "burger food"],
  ["fries", "\u{1f35f}", "chips food"],
  ["hotdog", "\u{1f32d}", "food"],
  ["taco", "\u{1f32e}", "food"],
  ["burrito", "\u{1f32f}", "food"],
  ["sushi", "\u{1f363}", "food"],
  ["ramen", "\u{1f35c}", "noodles soup"],
  ["spaghetti", "\u{1f35d}", "pasta"],
  ["rice", "\u{1f35a}", "food"],
  ["curry", "\u{1f35b}", "food"],
  ["green_salad salad", "\u{1f957}", "food healthy"],
  ["popcorn", "\u{1f37f}", "movie"],
  ["doughnut", "\u{1f369}", "donut sweet"],
  ["cookie", "\u{1f36a}", "sweet biscuit"],
  ["cake", "\u{1f370}", "sweet dessert"],
  ["birthday", "\u{1f382}", "cake party"],
  ["chocolate_bar", "\u{1f36b}", "sweet"],
  ["candy", "\u{1f36c}", "sweet"],
  ["icecream", "\u{1f366}", "sweet dessert"],
  ["coffee", "\u2615", "cafe espresso morning"],
  ["tea", "\u{1f375}", "drink"],
  ["beer", "\u{1f37a}", "drink pub"],
  ["beers", "\u{1f37b}", "cheers drinks"],
  ["wine_glass", "\u{1f377}", "wine drink"],
  ["cocktail", "\u{1f378}", "drink"],
  ["tropical_drink", "\u{1f379}", "drink vacation"],
  ["champagne", "\u{1f37e}", "celebrate bottle"],
  ["milk_glass", "\u{1f95b}", "drink"],
  ["cup_with_straw", "\u{1f964}", "drink soda"],
  ["plate_with_cutlery", "\u{1f37d}\ufe0f", "dinner meal"],
  ["fork_and_knife", "\u{1f374}", "meal restaurant"],
  ["house", "\u{1f3e0}", "home"],
  ["house_with_garden", "\u{1f3e1}", "home"],
  ["office", "\u{1f3e2}", "work building"],
  ["hospital", "\u{1f3e5}", "doctor"],
  ["school", "\u{1f3eb}", "education"],
  ["bank", "\u{1f3e6}", "money"],
  ["hotel", "\u{1f3e8}", "travel"],
  ["tent", "\u26fa", "camping"],
  ["mountain", "\u26f0\ufe0f", "hiking"],
  ["beach_umbrella", "\u{1f3d6}\ufe0f", "beach vacation"],
  ["desert_island", "\u{1f3dd}\ufe0f", "island vacation"],
  ["world_map", "\u{1f5fa}\ufe0f", "map travel"],
  ["car red_car", "\u{1f697}", "drive"],
  ["taxi", "\u{1f695}", "cab"],
  ["bus", "\u{1f68c}", "transport"],
  ["train2 train", "\u{1f686}", "transport rail"],
  ["bike", "\u{1f6b2}", "bicycle cycle"],
  ["airplane", "\u2708\ufe0f", "flight plane travel"],
  ["rocket", "\u{1f680}", "launch ship space"],
  ["ship", "\u{1f6a2}", "boat"],
  ["sailboat", "\u26f5", "boat"],
  ["anchor", "\u2693", "ship"],
  ["fuelpump", "\u26fd", "gas petrol"],
  ["vertical_traffic_light", "\u{1f6a6}", "traffic"],
  ["construction", "\u{1f6a7}", "wip work"],
  ["luggage", "\u{1f9f3}", "travel suitcase packing"],
  ["hourglass", "\u231b", "time wait"],
  ["hourglass_flowing_sand", "\u23f3", "time wait"],
  ["watch", "\u231a", "time"],
  ["alarm_clock", "\u23f0", "alarm time reminder"],
  ["stopwatch", "\u23f1\ufe0f", "timer"],
  ["timer_clock", "\u23f2\ufe0f", "timer"],
  ["calendar", "\u{1f4c6}", "date schedule"],
  ["date", "\u{1f4c5}", "calendar schedule"],
  ["spiral_calendar", "\u{1f5d3}\ufe0f", "calendar schedule"],
  ["tada", "\u{1f389}", "party celebrate congrats hooray"],
  ["confetti_ball", "\u{1f38a}", "party celebrate"],
  ["balloon", "\u{1f388}", "party birthday"],
  ["gift", "\u{1f381}", "present birthday"],
  ["ribbon", "\u{1f380}", "gift"],
  ["trophy", "\u{1f3c6}", "win award prize"],
  ["medal_sports", "\u{1f3c5}", "award"],
  ["1st_place_medal", "\u{1f947}", "gold first winner"],
  ["2nd_place_medal", "\u{1f948}", "silver second"],
  ["3rd_place_medal", "\u{1f949}", "bronze third"],
  ["soccer", "\u26bd", "football sport"],
  ["basketball", "\u{1f3c0}", "sport"],
  ["football", "\u{1f3c8}", "sport"],
  ["tennis", "\u{1f3be}", "sport"],
  ["dart", "\u{1f3af}", "target goal bullseye"],
  ["video_game", "\u{1f3ae}", "game controller"],
  ["game_die", "\u{1f3b2}", "dice game"],
  ["chess_pawn", "\u265f\ufe0f", "chess strategy"],
  ["jigsaw", "\u{1f9e9}", "puzzle piece"],
  ["art", "\u{1f3a8}", "paint palette design"],
  ["performing_arts", "\u{1f3ad}", "theater"],
  ["clapper", "\u{1f3ac}", "movie film"],
  ["microphone", "\u{1f3a4}", "sing karaoke"],
  ["headphones", "\u{1f3a7}", "music"],
  ["musical_note", "\u{1f3b5}", "music"],
  ["notes", "\u{1f3b6}", "music"],
  ["guitar", "\u{1f3b8}", "music"],
  ["musical_keyboard", "\u{1f3b9}", "piano music"],
  ["camera", "\u{1f4f7}", "photo"],
  ["movie_camera", "\u{1f3a5}", "film video"],
  ["tv", "\u{1f4fa}", "television"],
  ["radio", "\u{1f4fb}", "music"],
  ["iphone", "\u{1f4f1}", "phone mobile"],
  ["phone telephone", "\u260e\ufe0f", "call"],
  ["computer", "\u{1f4bb}", "laptop"],
  ["desktop_computer", "\u{1f5a5}\ufe0f", "computer screen"],
  ["keyboard", "\u2328\ufe0f", "type"],
  ["computer_mouse", "\u{1f5b1}\ufe0f", "mouse click"],
  ["printer", "\u{1f5a8}\ufe0f", "print"],
  ["floppy_disk", "\u{1f4be}", "save"],
  ["cd", "\u{1f4bf}", "disc"],
  ["battery", "\u{1f50b}", "power charge"],
  ["electric_plug", "\u{1f50c}", "power"],
  ["bulb", "\u{1f4a1}", "idea light tip"],
  ["flashlight", "\u{1f526}", "light"],
  ["candle", "\u{1f56f}\ufe0f", "light"],
  ["mag", "\u{1f50d}", "search find zoom"],
  ["mag_right", "\u{1f50e}", "search find"],
  ["lock", "\u{1f512}", "locked secure private"],
  ["unlock", "\u{1f513}", "unlocked open"],
  ["key", "\u{1f511}", "password"],
  ["old_key", "\u{1f5dd}\ufe0f", "key"],
  ["hammer", "\u{1f528}", "tool build"],
  ["wrench", "\u{1f527}", "tool fix"],
  ["nut_and_bolt", "\u{1f529}", "tool"],
  ["gear", "\u2699\ufe0f", "settings cog"],
  ["hammer_and_wrench", "\u{1f6e0}\ufe0f", "tools fix build"],
  ["toolbox", "\u{1f9f0}", "tools"],
  ["magnet", "\u{1f9f2}", "attract"],
  ["link", "\u{1f517}", "url chain"],
  ["paperclip", "\u{1f4ce}", "attach"],
  ["paperclips", "\u{1f587}\ufe0f", "attach"],
  ["pushpin", "\u{1f4cc}", "pin"],
  ["round_pushpin", "\u{1f4cd}", "pin location place"],
  ["scissors", "\u2702\ufe0f", "cut"],
  ["pencil2", "\u270f\ufe0f", "pencil write edit"],
  ["black_nib", "\u2712\ufe0f", "pen write"],
  ["pen", "\u{1f58a}\ufe0f", "write"],
  ["paintbrush", "\u{1f58c}\ufe0f", "paint"],
  ["crayon", "\u{1f58d}\ufe0f", "draw"],
  ["memo pencil", "\u{1f4dd}", "note write"],
  ["page_facing_up", "\u{1f4c4}", "document page"],
  ["page_with_curl", "\u{1f4c3}", "document"],
  ["bookmark_tabs", "\u{1f4d1}", "tabs"],
  ["bar_chart", "\u{1f4ca}", "chart stats graph"],
  ["chart_with_upwards_trend", "\u{1f4c8}", "chart growth up graph"],
  ["chart_with_downwards_trend", "\u{1f4c9}", "chart down graph"],
  ["clipboard", "\u{1f4cb}", "list tasks"],
  ["card_index", "\u{1f4c7}", "cards"],
  ["file_folder", "\u{1f4c1}", "folder"],
  ["open_file_folder", "\u{1f4c2}", "folder"],
  ["card_index_dividers", "\u{1f5c2}\ufe0f", "folders"],
  ["wastebasket", "\u{1f5d1}\ufe0f", "trash bin delete"],
  ["package", "\u{1f4e6}", "box parcel shipping"],
  ["email envelope", "\u2709\ufe0f", "mail letter"],
  ["e-mail", "\u{1f4e7}", "mail"],
  ["inbox_tray", "\u{1f4e5}", "inbox"],
  ["outbox_tray", "\u{1f4e4}", "outbox"],
  ["mailbox", "\u{1f4eb}", "mail"],
  ["postbox", "\u{1f4ee}", "mail"],
  ["newspaper", "\u{1f4f0}", "news"],
  ["books", "\u{1f4da}", "library read study"],
  ["book open_book", "\u{1f4d6}", "read"],
  ["notebook", "\u{1f4d3}", "notes"],
  ["notebook_with_decorative_cover", "\u{1f4d4}", "notes"],
  ["closed_book", "\u{1f4d5}", "book"],
  ["green_book", "\u{1f4d7}", "book"],
  ["blue_book", "\u{1f4d8}", "book"],
  ["orange_book", "\u{1f4d9}", "book"],
  ["ledger", "\u{1f4d2}", "notes"],
  ["bookmark", "\u{1f516}", "save"],
  ["label", "\u{1f3f7}\ufe0f", "tag"],
  ["moneybag", "\u{1f4b0}", "money"],
  ["dollar", "\u{1f4b5}", "money"],
  ["euro", "\u{1f4b6}", "money"],
  ["pound", "\u{1f4b7}", "money"],
  ["yen", "\u{1f4b4}", "money"],
  ["credit_card", "\u{1f4b3}", "money pay card"],
  ["gem", "\u{1f48e}", "diamond jewel"],
  ["briefcase", "\u{1f4bc}", "work business"],
  ["school_satchel", "\u{1f392}", "school bag backpack"],
  ["mortar_board", "\u{1f393}", "graduation school"],
  ["shopping_cart", "\u{1f6d2}", "shop groceries"],
  ["shopping", "\u{1f6cd}\ufe0f", "bags shop"],
  ["bell", "\u{1f514}", "notification alert"],
  ["no_bell", "\u{1f515}", "mute"],
  ["loudspeaker", "\u{1f4e2}", "announce"],
  ["mega", "\u{1f4e3}", "megaphone announce"],
  ["pill", "\u{1f48a}", "medicine"],
  ["syringe", "\u{1f489}", "vaccine"],
  ["dna", "\u{1f9ec}", "biology"],
  ["microscope", "\u{1f52c}", "science lab"],
  ["telescope", "\u{1f52d}", "space astronomy"],
  ["test_tube", "\u{1f9ea}", "science lab"],
  ["broom", "\u{1f9f9}", "clean"],
  ["soap", "\u{1f9fc}", "clean wash"],
  ["toilet", "\u{1f6bd}", "bathroom"],
  ["bathtub", "\u{1f6c1}", "bath"],
  ["bed", "\u{1f6cf}\ufe0f", "sleep"],
  ["couch_and_lamp", "\u{1f6cb}\ufe0f", "home living"],
  ["door", "\u{1f6aa}", "home"],
  ["shirt tshirt", "\u{1f455}", "clothes"],
  ["jeans", "\u{1f456}", "clothes"],
  ["dress", "\u{1f457}", "clothes"],
  ["eyeglasses", "\u{1f453}", "glasses"],
  ["dark_sunglasses", "\u{1f576}\ufe0f", "sunglasses"],
  ["crown", "\u{1f451}", "king queen"],
  ["tophat", "\u{1f3a9}", "hat"],
  ["lipstick", "\u{1f484}", "makeup"],
  ["ring", "\u{1f48d}", "wedding engaged"],
  ["rotating_light", "\u{1f6a8}", "alert siren emergency"],
  ["bomb", "\u{1f4a3}", "explode"],
  ["crystal_ball", "\u{1f52e}", "fortune future"],
  ["magic_wand", "\u{1fa84}", "magic"],
  ["nazar_amulet", "\u{1f9ff}", "luck"],
  ["moyai", "\u{1f5ff}", "stone face"],
  ["checkered_flag", "\u{1f3c1}", "finish race"],
  ["triangular_flag_on_post", "\u{1f6a9}", "flag red"],
  ["white_flag", "\u{1f3f3}\ufe0f", "surrender"],
  ["black_flag", "\u{1f3f4}", "flag"],
  ["rainbow_flag", "\u{1f3f3}\ufe0f\u200d\u{1f308}", "pride"],
  ["white_check_mark", "\u2705", "done check yes complete"],
  ["heavy_check_mark", "\u2714\ufe0f", "done check yes"],
  ["ballot_box_with_check", "\u2611\ufe0f", "done check"],
  ["x", "\u274c", "no wrong cross cancel"],
  ["negative_squared_cross_mark", "\u274e", "no cross"],
  ["heavy_plus_sign", "\u2795", "plus add"],
  ["heavy_minus_sign", "\u2796", "minus"],
  ["heavy_multiplication_x", "\u2716\ufe0f", "times multiply"],
  ["heavy_division_sign", "\u2797", "divide"],
  ["question", "\u2753", "what help"],
  ["grey_question", "\u2754", "what"],
  ["exclamation heavy_exclamation_mark", "\u2757", "important bang"],
  ["grey_exclamation", "\u2755", "important"],
  ["bangbang", "\u203c\ufe0f", "important"],
  ["interrobang", "\u2049\ufe0f", "what"],
  ["warning", "\u26a0\ufe0f", "caution alert"],
  ["no_entry", "\u26d4", "stop forbidden"],
  ["no_entry_sign", "\u{1f6ab}", "forbidden no"],
  ["stop_sign", "\u{1f6d1}", "stop"],
  ["recycle", "\u267b\ufe0f", "environment"],
  ["infinity", "\u267e\ufe0f", "forever"],
  ["red_circle", "\u{1f534}", "red dot"],
  ["orange_circle", "\u{1f7e0}", "orange dot"],
  ["yellow_circle", "\u{1f7e1}", "yellow dot"],
  ["green_circle", "\u{1f7e2}", "green dot"],
  ["large_blue_circle blue_circle", "\u{1f535}", "blue dot"],
  ["purple_circle", "\u{1f7e3}", "purple dot"],
  ["brown_circle", "\u{1f7e4}", "brown dot"],
  ["black_circle", "\u26ab", "dot"],
  ["white_circle", "\u26aa", "dot"],
  ["red_square", "\u{1f7e5}", "red"],
  ["orange_square", "\u{1f7e7}", "orange"],
  ["yellow_square", "\u{1f7e8}", "yellow"],
  ["green_square", "\u{1f7e9}", "green"],
  ["blue_square", "\u{1f7e6}", "blue"],
  ["purple_square", "\u{1f7ea}", "purple"],
  ["arrow_right", "\u27a1\ufe0f", "right next"],
  ["arrow_left", "\u2b05\ufe0f", "left back"],
  ["arrow_up", "\u2b06\ufe0f", "up"],
  ["arrow_down", "\u2b07\ufe0f", "down"],
  ["arrows_counterclockwise", "\u{1f504}", "refresh reload sync"],
  ["repeat", "\u{1f501}", "loop again"],
  ["fast_forward", "\u23e9", "forward"],
  ["rewind", "\u23ea", "back"],
  ["arrow_forward", "\u25b6\ufe0f", "play"],
  ["pause_button", "\u23f8\ufe0f", "pause"],
  ["stop_button", "\u23f9\ufe0f", "stop"],
  ["record_button", "\u23fa\ufe0f", "record"],
  ["new", "\u{1f195}", "fresh"],
  ["free", "\u{1f193}", "gratis"],
  ["up", "\u{1f199}", "update"],
  ["cool", "\u{1f192}", "nice"],
  ["ok", "\u{1f197}", "okay"],
  ["sos", "\u{1f198}", "help emergency"],
  ["information_source", "\u2139\ufe0f", "info"],
  ["copyright", "\u00a9\ufe0f", "c"],
  ["registered", "\u00ae\ufe0f", "r"],
  ["tm", "\u2122\ufe0f", "trademark"],
  ["hash", "\u0023\ufe0f\u20e3", "number"],
  ["zero", "\u0030\ufe0f\u20e3", "0 number"],
  ["one", "\u0031\ufe0f\u20e3", "1 number"],
  ["two", "\u0032\ufe0f\u20e3", "2 number"],
  ["three", "\u0033\ufe0f\u20e3", "3 number"],
  ["four", "\u0034\ufe0f\u20e3", "4 number"],
  ["five", "\u0035\ufe0f\u20e3", "5 number"],
  ["six", "\u0036\ufe0f\u20e3", "6 number"],
  ["seven", "\u0037\ufe0f\u20e3", "7 number"],
  ["eight", "\u0038\ufe0f\u20e3", "8 number"],
  ["nine", "\u0039\ufe0f\u20e3", "9 number"],
  ["keycap_ten", "\u{1f51f}", "10 number"],
  ["peace_symbol", "\u262e\ufe0f", "peace"],
  ["yin_yang", "\u262f\ufe0f", "balance"],
  ["atom_symbol", "\u269b\ufe0f", "science atom"],
  ["trident", "\u{1f531}", "symbol"],
  ["beginner", "\u{1f530}", "new start"],
  ["radioactive", "\u2622\ufe0f", "danger"],
  ["biohazard", "\u2623\ufe0f", "danger"],
  ["mute", "\u{1f507}", "silent sound off"],
  ["speaker", "\u{1f508}", "sound"],
  ["sound", "\u{1f509}", "volume"],
  ["loud_sound", "\u{1f50a}", "volume loud"],
  ["heavy_dollar_sign", "\u{1f4b2}", "money"],
  ["currency_exchange", "\u{1f4b1}", "money"]
]

// The ones people use most, offered first when others match as well.
var POPULAR = ("+1 heart tada fire rocket joy smile white_check_mark eyes thinking pray clap 100 sparkles star " +
  "warning bulb memo x wave muscle sob heart_eyes sunglasses ok_hand raised_hands wink blush slightly_smiling_face " +
  "sweat_smile grin laughing rofl cry coffee calendar date pushpin books bug zap lock link gift trophy dart " +
  "boom bell hourglass alarm_clock heavy_check_mark question exclamation point_right arrow_right house " +
  "computer phone email moneybag chart_with_upwards_trend bar_chart construction hammer_and_wrench gear").split(" ")

var parsed = null
function all() {
  if (parsed) return parsed
  parsed = LIST.map(function(r, i) {
    var codes = r[0].split(" ")
    var rank = POPULAR.indexOf(codes[0])
    return { codes: codes, emoji: r[1], words: r[2] ? r[2].split(" ") : [], order: rank >= 0 ? rank - POPULAR.length : i }
  })
  return parsed
}

// What's typed after ":" to find one: letters, digits, "_", "+" and "-".
function isQuery(text) { return /^[A-Za-z0-9_+-]+$/.test(String(text || "")) }

// The emoji called exactly `name` ("rocket", "+1"), or "".
function exact(name) {
  var q = String(name || "").toLowerCase()
  var list = all()
  for (var i = 0; i < list.length; i++) if (list[i].codes.indexOf(q) >= 0) return list[i].emoji
  return ""
}

// Emoji for what's typed after ":", best first: [{ emoji, code }], with the
// name that matched. A name that is it comes first, then names that start
// with it, then names with a part that does, then the other words.
function find(query, max) {
  var q = String(query || "").toLowerCase()
  if (!isQuery(q)) return []
  var hits = []
  all().forEach(function(e) {
    var rank = -1
    var code = e.codes[0]
    e.codes.forEach(function(c) {
      var r = c === q ? 0 : c.indexOf(q) === 0 ? 1 : c.split(/[_-]/).some(function(part) { return part.indexOf(q) === 0 }) ? 2 : -1
      if (r >= 0 && (rank < 0 || r < rank)) { rank = r; code = c }
    })
    if (rank < 0 && e.words.some(function(w) { return w.indexOf(q) === 0 })) rank = 3
    if (rank >= 0) hits.push({ emoji: e.emoji, code: code, rank: rank, order: e.order })
  })
  hits.sort(function(a, b) { return a.rank - b.rank || a.order - b.order })
  return hits.slice(0, max || 8).map(function(h) { return { emoji: h.emoji, code: h.code } })
}
